spring.application.name=digital-library

spring.datasource.url=jdbc:mysql://localhost:3306/minor_project89?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
library.book-issuance.max-threshold=3
library.book-issuance.duration=15
library.book-return.fine-per-day=1