spring.application.name=digital-library

spring.datasource.url=jdbc:mysql://localhost:3306/digital_library_89?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update